import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App Nick",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Link href="/" >Home</Link>
          <Link href="/team" >Team</Link>
          <Link href="/about" >About</Link>
          <Link href="/team/aboutteam" >About team</Link>
        </nav>
        <h1>Main Header</h1>
        {children}
      </body>
    </html>
  );
}
