import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Team",
    description: "Generated by create next app",
  };
  

export default function Team () {
    return (
        <h1>Team</h1>
    )
}